# Generated by Django 4.0.3 on 2022-05-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='decription',
            new_name='desription',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
