# Generated by Django 4.0.3 on 2022-07-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='content',
            field=models.FileField(upload_to='media'),
        ),
    ]
