# Generated by Django 4.0.3 on 2022-07-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_sheet_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='content',
            field=models.FileField(upload_to='.'),
        ),
    ]
